name: snap

on:
  # Manually trigger this from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Type'
        required: true
        default: 'stable'
        type: choice
        options:
        - lts
        - stable

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
        - ${{ inputs.release }}
        platform:
        - amd64
        - i386
        - arm64
        - armhf
    continue-on-error: ${{ matrix.platform == 'armhf' }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.8.0
        arch: x64
    - name: Generate snapcraft.yaml
      run: |
        cd scripts/
        julia --project=. -e 'using Pkg; Pkg.instantiate()'
        julia --project=. create-snapcraft-yaml.jl "${{ inputs.release }}"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build Snap
      uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: snapcraft
      with:
        architecture: ${{ matrix.platform }}
    - name: Upload and Release
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: ${{ inputs.release == 'lts' && 'lts/stable' || inputs.release }}
